# Use an official Node.js runtime as a parent image
FROM node:17

# Create and set the working directory in the container
WORKDIR /app

# install app dependencies
COPY frontend/package.json ./
COPY frontend/package-lock.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the frontend application code into the container
COPY . ./

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run your React application
CMD ["npm", "start"]