# Generated by Django 4.0.10 on 2023-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_created_at_campaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
