# Generated by Django 4.0.10 on 2023-09-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_user_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='delay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='next_step',
            field=models.CharField(default='65tyr', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='step_id',
            field=models.CharField(default='56uhv', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='type',
            field=models.CharField(default='email', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SequenceEmailChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('preview_text', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.sequence')),
            ],
        ),
    ]
