# Generated by Django 4.0.10 on 2023-09-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_sequence_delay_sequence_next_step_sequence_step_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sequenceemailchannel',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
