# Generated by Django 4.0.10 on 2023-09-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_sequence_data_alter_sequence_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='next_step',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
